name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test: 
    name: "Build && Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkput Code"
        uses: actions/checkout@v4


      - name: "Set up Go 1.21.8"
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.8'
	  cache: true


      - name: "Install Dependencies"
	run: |
	  go mod tidy
	  go get github.com/pelletier/go-toml/v2@2.0.6

      - name: "Build Project"
	run: go build -v -o listaPro

      - name: "Run Unit Tests"
	run: go test -v ./...

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: app-artifacts
          path: | 
            listaPro
            .env.exemplo
            go.mod
            go.sum
	  
