name: Go CD

on:
  push:
    brances: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps: 
    - name: Checkout do codigo
      uses: actions/checkout@v3

    - name: Install o Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'


    - name: Build do projeto
      run: go build -v ./...

    - name: Tests
      run: go test -v ./...
