name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4


    - name: Setup Go
      uses: actions/setup-go@v4
      with:
	go-version: '1.21.8'

    - name: Build
      run: go build -v -o listaPro

    - name: Run Tests
      run: go test -v ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          listaPro
          .env.example
          go.mod
	  go.sum

