name: Go CD

on:
  push:
    brances: 
      - main


jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest


    steps: 
    - name: Checkout do codigo
      uses: actions/checkout@v4

    - name: Install SSH 
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


    - name: Deploy to EC2 vi SSH
      run: |
        ssh ec2-user@10.0.6.223 'cd /home/ec2-user/listaPro && git pull && go build -o app && systemctl restart app.service'
