name: CD pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
	uses: actions/download-artifact@v4
	with:
	  name: build-artifacts
 
      - name: Deploy
 	uses: appleboy/ssh-action@master
	with:
	  host: ${{ secrets.SERVER_IP }}
	  username: ec2-user
	  key: ${{ secrets.SHH_PRIVATE_KEY}}
	  script: | 
	    sudo systemctl stop listaPro.service
	    mv listaPro /home/ec2-user/listaPro/
	    sudo systemctl restart listaPro.service
