name: GO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v4

    - name: Configurar Go 
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Baixar dependencias
      run: go mod tidy

    - name: Verificar erros com go vet
      run: go vet ./...

    - name: Rodar
      run: go test -v ./...

